import { Quiz } from '@/types'

export const QUIZZES: Quiz[] = [
  {
    id: 'ele-gosta-de-mim',
    slug: 'ele-gosta-de-mim',
    title: 'Ele Gosta de Mim?',
    description: 'Descubra o que os sinais realmente significam — e o que ele sente, mas nao fala.',
    category: 'relacionamentos',
    emoji: '💫',
    cta_text: 'Descubra o que ele realmente sente',
    free_questions: [
      {
        id: 'q1',
        text: 'Como ele age quando voces estao em grupo?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Me ignora completamente' },
          { id: 'b', text: 'Me trata como qualquer outra pessoa' },
          { id: 'c', text: 'Me inclui nas conversas com frequencia' },
          { id: 'd', text: 'Parece que so fala comigo' },
        ],
      },
      {
        id: 'q2',
        text: 'Com que frequencia ele inicia contato?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Quase nunca' },
          { id: 'b', text: 'Apenas quando precisa de algo' },
          { id: 'c', text: 'Algumas vezes por semana' },
          { id: 'd', text: 'Todo dia, sem razao aparente' },
        ],
      },
      {
        id: 'q3',
        text: 'Quando voces conversam, ele pergunta sobre sua vida?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Nao, ele so fala de si mesmo' },
          { id: 'b', text: 'As vezes, educadamente' },
          { id: 'c', text: 'Sim, com interesse genuino' },
          { id: 'd', text: 'Sim, lembra de detalhes que eu disse antes' },
        ],
      },
      {
        id: 'q4',
        text: 'Qual e o contato fisico entre voces?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Nenhum, mantem distancia' },
          { id: 'b', text: 'So o normal para amigos' },
          { id: 'c', text: 'Toca meu braco/ombro com frequencia' },
          { id: 'd', text: 'Claramente procura contato fisico' },
        ],
      },
      {
        id: 'q5',
        text: 'Quanto tempo leva para ele responder suas mensagens?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Demora horas ou dias' },
          { id: 'b', text: 'Varia muito, imprevisivel' },
          { id: 'c', text: 'Geralmente rapido' },
          { id: 'd', text: 'Quase imediato, sempre' },
        ],
      },
      {
        id: 'q6',
        text: 'O que acontece quando voce menciona outros caras?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Ele nao liga, muda de assunto' },
          { id: 'b', text: 'Reage normalmente' },
          { id: 'c', text: 'Faz perguntas discretas sobre eles' },
          { id: 'd', text: 'Claramente fica diferente, mais serio' },
        ],
      },
    ],
    premium_questions: [
      {
        id: 'pq1',
        text: 'Descreva um momento especifico em que voce sentiu que ele poderia gostar de voce.',
        type: 'free_text',
      },
      {
        id: 'pq2',
        text: 'Em uma escala de 1 a 10, qual e a sua intuicao sobre o interesse dele?',
        type: 'scale',
        scale_min: 1,
        scale_max: 10,
        scale_min_label: 'So amizade',
        scale_max_label: 'Tem interesse claro',
      },
      {
        id: 'pq3',
        text: 'Quando voces estao juntos, como ele te faz sentir?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Invisivel ou ignorada' },
          { id: 'b', text: 'Confortavel, como com qualquer amigo' },
          { id: 'c', text: 'Especial e valorizada' },
          { id: 'd', text: 'Eletrica, com tensao entre nos' },
        ],
      },
      {
        id: 'pq4',
        text: 'Ele ja compartilhou algo pessoal ou vulneravel com voce?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Nunca, ele e fechado com todos' },
          { id: 'b', text: 'Coisas superficiais apenas' },
          { id: 'c', text: 'Sim, coisas que normalmente nao conta' },
          { id: 'd', text: 'Compartilhou segredos profundos comigo' },
        ],
      },
      {
        id: 'pq5',
        text: 'O que voce acha que impede ele de ser mais direto, se e que algo impede?',
        type: 'free_text',
      },
      {
        id: 'pq6',
        text: 'Ele faz planos futuros incluindo voce?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Nunca menciona o futuro' },
          { id: 'b', text: 'Planos imediatos, sem comprometimento' },
          { id: 'c', text: 'As vezes sugere coisas para fazermos' },
          { id: 'd', text: 'Frequentemente faz planos que me incluem' },
        ],
      },
      {
        id: 'pq7',
        text: 'Em uma escala de 1 a 10, o quanto voce quer que ele goste de voce?',
        type: 'scale',
        scale_min: 1,
        scale_max: 10,
        scale_min_label: 'Curiosidade apenas',
        scale_max_label: 'Quero muito',
      },
    ],
    created_at: '2026-03-22T00:00:00Z',
  },
  {
    id: 'qual-seu-padrao-amoroso',
    slug: 'qual-seu-padrao-amoroso',
    title: 'Qual e o Seu Padrao Amoroso?',
    description: 'Seu estilo de amar revela muito sobre por que voce atrai quem atrai.',
    category: 'relacionamentos',
    emoji: '❤️',
    cta_text: 'Descubra seu padrao de amor',
    free_questions: [
      {
        id: 'q1',
        text: 'Quando alguem que voce gosta some por um tempo, voce:',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Fico aliviada, preciso de espaco' },
          { id: 'b', text: 'Espero tranquilamente o contato' },
          { id: 'c', text: 'Fico preocupada mas nao demonstro' },
          { id: 'd', text: 'Fico ansiosa e mando mensagem' },
        ],
      },
      {
        id: 'q2',
        text: 'Para voce, a coisa mais importante em um relacionamento e:',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Independencia e espaco' },
          { id: 'b', text: 'Confianca e seguranca' },
          { id: 'c', text: 'Paixao e intensidade' },
          { id: 'd', text: 'Atencao e validacao constante' },
        ],
      },
      {
        id: 'q3',
        text: 'Voce costuma terminar relacionamentos ou ser terminada?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Quase sempre eu termino' },
          { id: 'b', text: 'Geralmente mutual ou tranquilo' },
          { id: 'c', text: 'Varia muito' },
          { id: 'd', text: 'Geralmente me terminam' },
        ],
      },
      {
        id: 'q4',
        text: 'Quando briga com parceiro, voce tende a:',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Se recolher e ficar em silencio' },
          { id: 'b', text: 'Conversar e resolver logo' },
          { id: 'c', text: 'Exagerar na reacao e se arrepender depois' },
          { id: 'd', text: 'Buscar reaprovacao imediatamente' },
        ],
      },
      {
        id: 'q5',
        text: 'Como voce se sente com a ideia de ficar solteira por um longo tempo?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Liviada, prefiro estar so' },
          { id: 'b', text: 'Ok, aproveito o tempo' },
          { id: 'c', text: 'Um pouco desconfortavel' },
          { id: 'd', text: 'Muito desconfortavel, me angustia' },
        ],
      },
    ],
    premium_questions: [
      {
        id: 'pq1',
        text: 'Descreva o relacionamento mais significativo que voce ja teve.',
        type: 'free_text',
      },
      {
        id: 'pq2',
        text: 'Em uma escala de 1 a 10, o quanto voce depende de validacao do parceiro?',
        type: 'scale',
        scale_min: 1,
        scale_max: 10,
        scale_min_label: 'Sou muito independente',
        scale_max_label: 'Preciso muito de validacao',
      },
      {
        id: 'pq3',
        text: 'Voce repete os mesmos tipos de relacionamento?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Nao, cada um e completamente diferente' },
          { id: 'b', text: 'Talvez, mas nao vejo um padrao claro' },
          { id: 'c', text: 'Sim, percebo alguns padroes' },
          { id: 'd', text: 'Definitivamente, e frustrante' },
        ],
      },
      {
        id: 'pq4',
        text: 'O que voce mais teme em um relacionamento intimo?',
        type: 'free_text',
      },
      {
        id: 'pq5',
        text: 'Em uma escala de 1 a 10, o quao facil e para voce confiar em parceiros?',
        type: 'scale',
        scale_min: 1,
        scale_max: 10,
        scale_min_label: 'Muito dificil',
        scale_max_label: 'Confio facilmente',
      },
    ],
    created_at: '2026-03-22T00:00:00Z',
  },
  {
    id: 'qual-carreira-combina',
    slug: 'qual-carreira-combina',
    title: 'Qual Carreira Combina Com Quem Voce Realmente E?',
    description: 'Nao o que voce estudou — o que sua essencia pede.',
    category: 'carreira',
    emoji: '🧭',
    cta_text: 'Descubra seu caminho profissional real',
    free_questions: [
      {
        id: 'q1',
        text: 'O que te da mais energia no trabalho?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Resolver problemas complexos sozinho' },
          { id: 'b', text: 'Liderar e influenciar pessoas' },
          { id: 'c', text: 'Criar algo do zero' },
          { id: 'd', text: 'Ajudar e transformar vidas' },
        ],
      },
      {
        id: 'q2',
        text: 'Seu maior desafio profissional atual e:',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Falta de reconhecimento' },
          { id: 'b', text: 'Nao sei o que quero fazer' },
          { id: 'c', text: 'Ambiente ou pessoas toxicas' },
          { id: 'd', text: 'Nao ganho o suficiente' },
        ],
      },
      {
        id: 'q3',
        text: 'Se dinheiro nao fosse problema, voce faria:',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Arte, escrita ou musica' },
          { id: 'b', text: 'Construir um negocio proprio' },
          { id: 'c', text: 'Trabalhar com pessoas em sofrimento' },
          { id: 'd', text: 'Pesquisa ou algo intelectualmente estimulante' },
        ],
      },
      {
        id: 'q4',
        text: 'Como voce prefere trabalhar?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'So, com total autonomia' },
          { id: 'b', text: 'Em equipe pequena e focada' },
          { id: 'c', text: 'Em equipe grande com estrutura' },
          { id: 'd', text: 'Variado, hora so hora com gente' },
        ],
      },
      {
        id: 'q5',
        text: 'O que te faz adiar decisoes importantes de carreira?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Medo de errar ou decepcionar' },
          { id: 'b', text: 'Incerteza financeira' },
          { id: 'c', text: 'Opiniao de familia e amigos' },
          { id: 'd', text: 'Nao me sinto pronto ainda' },
        ],
      },
    ],
    premium_questions: [
      {
        id: 'pq1',
        text: 'Descreva um momento em que voce se sentiu completamente no seu elemento trabalhando.',
        type: 'free_text',
      },
      {
        id: 'pq2',
        text: 'Em uma escala de 1 a 10, o quao alinhado voce esta com seu trabalho atual?',
        type: 'scale',
        scale_min: 1,
        scale_max: 10,
        scale_min_label: 'Totalmente perdido',
        scale_max_label: 'Perfeitamente alinhado',
      },
      {
        id: 'pq3',
        text: 'Qual habilidade ou talento seu e mais subestimado pelos outros?',
        type: 'free_text',
      },
      {
        id: 'pq4',
        text: 'Voce priorizaria mais:',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Proposito e impacto' },
          { id: 'b', text: 'Liberdade e autonomia' },
          { id: 'c', text: 'Reconhecimento e status' },
          { id: 'd', text: 'Estabilidade e seguranca' },
        ],
      },
      {
        id: 'pq5',
        text: 'Em uma escala de 1 a 10, o quanto voce esta disposto a arriscar pela carreira dos sonhos?',
        type: 'scale',
        scale_min: 1,
        scale_max: 10,
        scale_min_label: 'Prefiro seguranca',
        scale_max_label: 'Aceito qualquer risco',
      },
    ],
    created_at: '2026-03-22T00:00:00Z',
  },
  {
    id: 'meu-eu-sombra',
    slug: 'meu-eu-sombra',
    title: 'Qual e o Seu Lado Sombra?',
    description: 'A parte de voce que voce nao admite — mas que controla muito mais do que imagina.',
    category: 'personalidade',
    emoji: '🌑',
    cta_text: 'Encontre o que voce esconde de si mesmo',
    free_questions: [
      {
        id: 'q1',
        text: 'O que mais te irrita nas outras pessoas?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Preguica e falta de ambicao' },
          { id: 'b', text: 'Arrogancia e ego' },
          { id: 'c', text: 'Necessidade excessiva de atencao' },
          { id: 'd', text: 'Inseguranca e vitimismo' },
        ],
      },
      {
        id: 'q2',
        text: 'Quando age de uma forma que nao gosta em si mesmo, voce costuma:',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Ignorar e fingir que nao aconteceu' },
          { id: 'b', text: 'Me punir mentalmente por dias' },
          { id: 'c', text: 'Justificar com circunstancias externas' },
          { id: 'd', text: 'Reconhecer e tentar entender' },
        ],
      },
      {
        id: 'q3',
        text: 'Qual e seu maior "vicio secreto" emocional?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Controle — preciso que as coisas sejam do meu jeito' },
          { id: 'b', text: 'Aprovacao — preciso que me valorizem' },
          { id: 'c', text: 'Fuga — evito conflitos e situacoes desconfortaveis' },
          { id: 'd', text: 'Intensidade — preciso de drama para me sentir vivo' },
        ],
      },
      {
        id: 'q4',
        text: 'Voce ja sabotou algo bom em sua vida?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Nao, nunca faria isso' },
          { id: 'b', text: 'Talvez sem perceber' },
          { id: 'c', text: 'Sim, percebo esse padrao' },
          { id: 'd', text: 'Sim, e e algo recorrente' },
        ],
      },
      {
        id: 'q5',
        text: 'O que as pessoas mais perto de voce reclamam de voce?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Que sou fechado e distante' },
          { id: 'b', text: 'Que sou controlador ou critico demais' },
          { id: 'c', text: 'Que sou impulsivo ou intenso demais' },
          { id: 'd', text: 'Que sumo ou me isolo' },
        ],
      },
    ],
    premium_questions: [
      {
        id: 'pq1',
        text: 'Descreva uma situacao recente em que voce agiu de uma forma que se arrependeu.',
        type: 'free_text',
      },
      {
        id: 'pq2',
        text: 'Em uma escala de 1 a 10, o quao honesto voce e consigo mesmo sobre seus defeitos?',
        type: 'scale',
        scale_min: 1,
        scale_max: 10,
        scale_min_label: 'Me iludo bastante',
        scale_max_label: 'Sou muito honesto',
      },
      {
        id: 'pq3',
        text: 'O que voce nunca admitiria publicamente sobre si mesmo?',
        type: 'free_text',
      },
      {
        id: 'pq4',
        text: 'Quando voce se sente ameacado, como reage?',
        type: 'mcq',
        options: [
          { id: 'a', text: 'Ataco antes de ser atacado' },
          { id: 'b', text: 'Me retiro completamente' },
          { id: 'c', text: 'Acordo interno, mas mostro calma' },
          { id: 'd', text: 'Expresso tudo na hora, mesmo exagerando' },
        ],
      },
      {
        id: 'pq5',
        text: 'Em uma escala de 1 a 10, o quanto voce se aceita como e?',
        type: 'scale',
        scale_min: 1,
        scale_max: 10,
        scale_min_label: 'Muito critico comigo',
        scale_max_label: 'Me aceito completamente',
      },
    ],
    created_at: '2026-03-22T00:00:00Z',
  },
]

export function getQuizBySlug(slug: string): Quiz | undefined {
  return QUIZZES.find((q) => q.slug === slug)
}

export const CATEGORIES = [
  { id: 'relacionamentos', name: 'Relacionamentos', emoji: '💫', description: 'Amor, desejo e conexao', color: 'from-pink-500/20 to-rose-500/20' },
  { id: 'personalidade', name: 'Personalidade', emoji: '🌑', description: 'Quem voce realmente e', color: 'from-violet-500/20 to-purple-500/20' },
  { id: 'carreira', name: 'Carreira', emoji: '🧭', description: 'Seu caminho e proposito', color: 'from-blue-500/20 to-cyan-500/20' },
  { id: 'vida', name: 'Decisoes de Vida', emoji: '✨', description: 'Clareza para o proximo passo', color: 'from-amber-500/20 to-orange-500/20' },
]
